import { animateUSDZ } from './usdz-animation.js';
import * as T from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { SVGLoader } from 'three/addons/loaders/SVGLoader.js';
import { USDZExporter } from 'three/addons/exporters/USDZExporter.js';
import { toCreasedNormals } from 'three/addons/utils/BufferGeometryUtils.js';
import { RoomEnvironment } from 'three/addons/environments/RoomEnvironment.js';
const $=id=>document.getElementById(id);
const state={shape:'coin',color:'gold',depth:12,bevel:20,metal:80,rough:25,scale:65,source:null};
const colors={gold:['#dbb963','香槟金'],silver:['#bdcbd7','铂金银'],rose:['#dca48c','玫瑰金'],violet:['#a899ec','极光紫']};
let backView=false;
let renderer,scene,camera,controls,model,texture=null,sequence=0,busy=false;
function dispose(group){group?.traverse(o=>{o.geometry?.dispose();if(o.material){for(const m of Array.isArray(o.material)?o.material:[o.material]){if(m.userData.inscription)m.map?.dispose();m.dispose()}}})}
function shape(){const s=new T.Shape();if(state.shape==='coin')s.absarc(0,0,1,0,Math.PI*2,false);else if(state.shape==='shield'){s.moveTo(-.84,.82);s.lineTo(.84,.82);s.bezierCurveTo(.98,-.25,.5,-.75,0,-1);s.bezierCurveTo(-.5,-.75,-.98,-.25,-.84,.82)}else{const n=state.shape==='hex'?6:120;for(let i=0;i<=n;i++){const a=i/n*Math.PI*2+Math.PI/2,r=state.shape==='flower'?.92+.08*Math.cos(a*12):1;i?s.lineTo(Math.cos(a)*r,Math.sin(a)*r):s.moveTo(Math.cos(a)*r,Math.sin(a)*r)}}return s}
function material(color=colors[state.color][0]){return new T.MeshStandardMaterial({color,metalness:state.metal/100,roughness:Math.max(.06,state.rough/100)})}
function extrude(s,depth,bevel=.02){const raw=new T.ExtrudeGeometry(s,{depth,bevelEnabled:bevel>0,bevelThickness:bevel,bevelSize:bevel,bevelSegments:12,steps:1,curveSegments:96});const smooth=toCreasedNormals(raw,Math.PI/3);raw.dispose();return smooth}
function addBack(next,depth,bevel){
const c=document.createElement('canvas');c.width=c.height=1024;const ctx=c.getContext('2d');ctx.textAlign='center';ctx.textBaseline='middle';
const title=$('title').value.trim()||'我的运动奖章',text=$('backText').value.trim(),date=$('backTime').value.replace('T','  ').replaceAll('-','.');
function draw(line,y,size,color){ctx.font='500 '+size+'px -apple-system,BlinkMacSystemFont,"PingFang SC",sans-serif';const width=ctx.measureText(line).width;ctx.save();ctx.translate(512,y);ctx.scale(Math.min(1,900/Math.max(1,width)),1);ctx.fillStyle='#fff3cf';ctx.fillText(line,0,2);ctx.fillStyle=color;ctx.fillText(line,0,0);ctx.restore()}
draw('PERSONAL ACHIEVEMENT',160,35,'#685024');draw(title,290,90,'#47381f');
const lines=[];for(const paragraph of text.split('\n')){let line='';for(const char of paragraph){ctx.font='44px -apple-system,BlinkMacSystemFont,"PingFang SC",sans-serif';if(ctx.measureText(line+char).width>840){lines.push(line);line=char}else line+=char}lines.push(line)}
const step=Math.min(85,260/Math.max(1,lines.length));lines.forEach((line,i)=>draw(line,420+i*step,Math.min(60,step*.72),'#685024'));
if(date)draw(date,810,52,'#685024');ctx.strokeStyle='#8c733a';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(350,720);ctx.lineTo(674,720);ctx.stroke();
const map=new T.CanvasTexture(c);map.colorSpace=T.SRGBColorSpace;const mat=new T.MeshStandardMaterial({map,transparent:false,alphaTest:.1,roughness:.85,metalness:.05});mat.userData.inscription=true;
const mesh=new T.Mesh(new T.PlaneGeometry(1.45,1.45),mat);mesh.name='Back_text_and_time';mesh.rotation.y=Math.PI;mesh.position.z=-depth/2-bevel-.002;next.add(mesh);
}
function build(){const next=new T.Group();next.name='Medal';const depth=state.depth*.01,bevel=Math.min(state.bevel*.001,depth*.4);const base=new T.Mesh(extrude(shape(),depth,bevel),material());base.name='Medal_base';base.position.z=-depth/2;next.add(base);
const rim=shape();rim.holes.push(new T.Path(shape().getPoints(128).map(p=>p.multiplyScalar(.91))));const border=new T.Mesh(extrude(rim,.018,.005),material());border.position.z=depth/2+bevel+.007;border.name='Raised_border';next.add(border);
const art=new T.Group();art.name=state.source?.kind==='svg'?'Extruded_SVG':'Artwork';let width=1.4;
if(state.source?.kind==='svg'){width=state.source.width;for(const part of state.source.parts){const g=extrude(part.shape,Math.max(.018,depth*.27)*width/1.4,.002*width);g.scale(1,-1,1);for(const attribute of Object.values(g.attributes)){const a=attribute.array,n=attribute.itemSize;for(let i=0;i<attribute.count;i+=3)for(let j=0;j<n;j++){const x=(i+1)*n+j,y=(i+2)*n+j,v=a[x];a[x]=a[y];a[y]=v}attribute.needsUpdate=true}g.translate(-state.source.center.x,state.source.center.y,0);const mesh=new T.Mesh(g,material(part.color));mesh.name='SVG_relief';art.add(mesh)}}else if(state.source?.kind==='png'){width=1;const mesh=new T.Mesh(new T.PlaneGeometry(state.source.width/Math.max(state.source.width,state.source.height),state.source.height/Math.max(state.source.width,state.source.height)),new T.MeshStandardMaterial({map:texture,transparent:false,alphaTest:.1,roughness:.65,metalness:0,side:T.FrontSide}));mesh.name='PNG_texture';art.add(mesh)}else{for(const [r,col,gap] of [[.58,'#fc3972',.5],[.42,'#b5fa35',.9],[.26,'#5be5e8',1.2]]){const mesh=new T.Mesh(new T.TorusGeometry(r,.065,12,96,Math.PI*2-gap),material(col));mesh.rotation.z=Math.PI/2;art.add(mesh)}}
const f=state.source?.kind==='png'?1.5*state.scale/65:1.4/width*state.scale/65;art.scale.setScalar(f);art.position.z=depth/2+bevel+.01;next.add(art);addBack(next,depth,bevel);if(model){next.quaternion.copy(model.quaternion);scene.remove(model);dispose(model)}model=next;scene.add(model);renderer.render(scene,camera)}
let lastDownloadURL=null;
function save(blob,ext){const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=($('title').value||'medal')+'.'+ext;document.body.append(a);a.click();a.remove();if(lastDownloadURL)URL.revokeObjectURL(lastDownloadURL);lastDownloadURL=url;let link=$('exportResult');if(!link){link=document.createElement('a');link.id='exportResult';document.querySelector('.export-actions').append(link)}link.href=url;link.download=a.download;link.textContent='再次下载 '+ext.toUpperCase();link.dataset.format=ext}
function resize(){const c=$('canvas'),w=c.clientWidth,h=c.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}
function init(){renderer=new T.WebGLRenderer({canvas:$('canvas'),antialias:true,alpha:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;scene=new T.Scene();camera=new T.PerspectiveCamera(35,1,.01,100);camera.position.set(.4,.25,4.8);controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.enablePan=false;controls.minDistance=2.8;controls.maxDistance=8;const pmrem=new T.PMREMGenerator(renderer);const room=new RoomEnvironment();scene.environment=pmrem.fromScene(room).texture;room.dispose();pmrem.dispose();scene.add(new T.HemisphereLight(0xffffff,0x8b9779,2));const light=new T.DirectionalLight(0xffffff,3);light.position.set(-3,4,5);scene.add(light);new ResizeObserver(resize).observe($('canvas'));resize();build();const reduced=matchMedia('(prefers-reduced-motion: reduce)');controls.addEventListener('start',()=>$('spin').checked=false);let last=0;renderer.setAnimationLoop(t=>{const dt=Math.min((t-last)/1000,.05);last=t;if(!busy&&$('spin').checked&&!reduced.matches)model.rotation.y+=dt*(Math.PI*2/9);model.position.y=$('spin').checked&&!reduced.matches&&!busy?.12*Math.sin(t/3000*Math.PI*2):0;controls.update();renderer.render(scene,camera)});$('status').textContent='真实 3D 已就绪 · SVG 拉伸 / PNG 贴图';$('download').disabled=false;$('usdz').disabled=false}
function sanitizeSVG(text){const doc=new DOMParser().parseFromString(text,'image/svg+xml');if(doc.querySelector('parsererror')||doc.documentElement.localName!=='svg')throw Error('SVG 文件格式不正确');if(doc.querySelector('script,foreignObject,image,use,style,animate,set,text,linearGradient,radialGradient,clipPath,mask,filter')||[...doc.querySelectorAll('*')].some(e=>[...e.attributes].some(a=>/^on/i.test(a.name)||/href/i.test(a.name)||/url\s*\(/i.test(a.value))))throw Error('请将文字/描边转为轮廓，使用纯色、无外部资源的 SVG');if(doc.querySelectorAll('*').length>3000||text.length>2000000)throw Error('SVG 太复杂，请简化路径后上传');return new XMLSerializer().serializeToString(doc)}
async function upload(file){if(!file||busy)return;const id=++sequence;try{if(file.size>10*1024*1024)throw Error('图片超过 10 MB');let next,newTexture=null;if(/\.svg$/i.test(file.name)||file.type==='image/svg+xml'){const text=sanitizeSVG(await file.text()),parsed=new SVGLoader().parse(text),parts=[];const box=new T.Box2();let points=0;for(const path of parsed.paths){const style=path.userData.style;if(style.stroke&&style.stroke!=='none')throw Error('请先把 SVG 描边转换为填充轮廓');if(style.fill==='none')continue;if(style.fillOpacity<1||style.opacity<1)throw Error('请使用不透明的 SVG 填充');for(const s of SVGLoader.createShapes(path)){const pts=s.getPoints(24);points+=pts.length;for(const p of pts)box.expandByPoint(p);parts.push({shape:s,color:path.color.clone()})}}if(!parts.length||box.isEmpty())throw Error('SVG 没有可拉伸的填充图形');if(points>30000||parts.length>500)throw Error('SVG 路径过多，请简化后上传');const size=box.getSize(new T.Vector2());if(!Math.max(size.x,size.y))throw Error('SVG 图形尺寸无效');next={kind:'svg',parts,width:Math.max(size.x,size.y),center:box.getCenter(new T.Vector2())}}else{const bytes=new Uint8Array(await file.slice(0,8).arrayBuffer());if(bytes.join(',')!=='137,80,78,71,13,10,26,10')throw Error('请选择有效 PNG 或 SVG');const url=URL.createObjectURL(file);try{const image=new Image();image.src=url;await image.decode();if(image.width*image.height>40000000)throw Error('PNG 尺寸过大，请缩小后上传');const c=document.createElement('canvas'),ratio=Math.min(1,2048/Math.max(image.width,image.height));c.width=Math.max(1,Math.round(image.width*ratio));c.height=Math.max(1,Math.round(image.height*ratio));c.getContext('2d').drawImage(image,0,0,c.width,c.height);newTexture=new T.CanvasTexture(c);newTexture.colorSpace=T.SRGBColorSpace;next={kind:'png',width:c.width,height:c.height}}finally{URL.revokeObjectURL(url)}}if(id!==sequence){newTexture?.dispose();return}const previous=state.source,previousTexture=texture;state.source=next;texture=newTexture;try{build()}catch(e){state.source=previous;texture=previousTexture;newTexture?.dispose();throw e}previousTexture?.dispose();$('status').textContent=(next.kind==='svg'?'已生成立体 SVG：':'已添加 PNG 贴图：')+file.name}catch(e){$('status').textContent=e.message}}
for(const key of ['depth','bevel','metal','rough','scale'])$(key).oninput=e=>{if(busy)return;state[key]=+e.target.value;$(key+'Value').value=e.target.value+(['depth','bevel'].includes(key)?'':'%');build()};document.querySelectorAll('[data-shape],[data-color]').forEach(b=>b.onclick=()=>{if(busy)return;const key=b.dataset.shape?'shape':'color';state[key]=b.dataset[key];document.querySelectorAll('[data-'+key+']').forEach(el=>el.classList.toggle('active',el===b));if(key==='color')$('material').textContent=colors[state.color][1];build()});let textTimer;function refreshText(){if(busy)return;clearTimeout(textTimer);textTimer=setTimeout(build,120)}$('title').oninput=()=>{$('awardTitle').textContent=$('title').value||'我的运动奖章';refreshText()};$('backText').oninput=refreshText;$('backTime').oninput=refreshText;$('flip').onclick=()=>{if(busy)return;backView=!backView;$('spin').checked=false;model.rotation.set(0,0,0);controls.reset();camera.position.set(0,.15,backView?-4.8:4.8);controls.update();$('flip').textContent=backView?'查看正面 ↺':'查看背面 ↺'};$('reset').onclick=()=>{controls.reset();model.rotation.set(0,0,0);backView=false;$('flip').textContent='查看背面 ↺'};$('file').onchange=e=>upload(e.target.files[0]);$('demo').onclick=()=>{if(busy)return;sequence++;state.source=null;texture?.dispose();texture=null;build();$('file').value='';$('status').textContent='已使用 3D 活动圆环示例'};const drop=$('drop');drop.ondragover=e=>{e.preventDefault();drop.classList.add('drag')};drop.ondragleave=()=>drop.classList.remove('drag');drop.ondrop=e=>{e.preventDefault();drop.classList.remove('drag');upload(e.dataTransfer.files[0])};
$('download').onclick=()=>{clearTimeout(textTimer);build();const old=renderer.getSize(new T.Vector2()),aspect=camera.aspect,dpr=renderer.getPixelRatio();try{renderer.setPixelRatio(1);renderer.setSize(2048,2048,false);camera.aspect=1;camera.updateProjectionMatrix();renderer.render(scene,camera);$('canvas').toBlob(blob=>{if(blob){save(blob,'png');$('status').textContent='PNG 已生成，请查看浏览器下载'}else $('status').textContent='PNG 导出失败'},'image/png')}finally{renderer.setPixelRatio(dpr);renderer.setSize(old.x,old.y,false);camera.aspect=aspect;camera.updateProjectionMatrix()}};
$('usdz').onclick=async()=>{if(busy)return;clearTimeout(textTimer);build();busy=true;$('usdz').disabled=true;$('usdz').textContent='正在生成 USDZ…';try{const exportScene=new T.Scene(),copy=model.clone(true);copy.rotation.set(0,0,0);copy.position.set(0,0,0);copy.scale.setScalar(.025);exportScene.add(copy);exportScene.updateMatrixWorld(true);const buffer=await new USDZExporter().parseAsync(exportScene,{maxTextureSize:2048,quickLookCompatible:true,includeAnchoringProperties:true});const animated=$('exportAnimation').checked?animateUSDZ(buffer):buffer;save(new Blob([animated],{type:'model/vnd.usdz+zip'}),'usdz');$('status').textContent=$('exportAnimation').checked?'动画 USDZ 已生成 · 9 秒旋转一圈':'静态 USDZ 已生成 · 奖章直径约 5 cm'}catch(e){console.error(e);$('status').textContent='USDZ 导出失败：'+e.message}finally{busy=false;$('usdz').disabled=false;$('usdz').textContent='下载 3D · USDZ ↓'}};
const now=new Date(),pad=n=>String(n).padStart(2,'0');$('backTime').value=now.getFullYear()+'-'+pad(now.getMonth()+1)+'-'+pad(now.getDate())+'T'+pad(now.getHours())+':'+pad(now.getMinutes());
try{init()}catch(e){console.error(e);$('status').textContent='3D 加载失败，请使用支持 WebGL 的浏览器';$('download').disabled=true;$('usdz').disabled=true}
